name = "bleak"
license = "MIT"
licenselink = "https://github.com/edyo/hugo-theme-bleak/blob/master/LICENSE.md"
description = "SPT variation of the bleak theme"
homepage = "http://www.spt.co.uk/"
tags = ["ghost", "minimal"]
features = ["", ""]
min_version = 0.15

[author]
  name = "Eduardo Bellido Bellido"
  homepage = "http://edubxb.net"

# If porting an existing theme
[original]
  name = "Peter Amende"
  homepage = "https://github.com/zutrinken"
  repo = "https://github.com/zutrinken/bleak"
